### ISSUE TITLE
Failed to create secure subchannel for secure name '192.168.137.4:6379'

### ISSUE THREAD

**Issue by holdbelief** [secretflow/secretflow#41] opened 2022-07-14 11:56 UTC
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

latest

### OS Platform and Distribution

Centos7.5

### What happend and What you expected to happen.

```shell
执行下面这个操作的时候
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats


抛出异常
(yinyu) [root@alice secretflow_cluster]# RAY_DISABLE_REMOTE_CODE=true RAY_SECURITY_CONFIG_PATH=config.yml RAY_USE_TLS=1 RAY_TLS_SERVER_CERT=servercert.pem RAY_TLS_SERVER_KEY=serverkey.pem RAY_TLS_CA_CERT=cacert.pem ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 192.168.137.4
E0714 07:48:09.783010834    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:09.783055834    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:09.783061834    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:09.783066534    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:10.785822614    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:10.785848214    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:10.785853214    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:10.785857714    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:11.787983491    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:11.788010492    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:11.788015492    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:11.788019492    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:12.790182069    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:12.790247570    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:12.790256170    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:12.790260470    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:13.792359247    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:13.792404647    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:13.792410247    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:13.792423847    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:14.794512125    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:14.794539725    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:14.794545325    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:14.794549725    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
2022-07-14 07:48:14,794	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
```

### Reproduction code to reproduce the issue.

```shell
执行下面这个操作的时候
RAY_DISABLE_REMOTE_CODE=true \
RAY_SECURITY_CONFIG_PATH=config.yml \
RAY_USE_TLS=1 \
RAY_TLS_SERVER_CERT=servercert.pem \
RAY_TLS_SERVER_KEY=serverkey.pem \
RAY_TLS_CA_CERT=cacert.pem \
ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats


抛出异常
(yinyu) [root@alice secretflow_cluster]# RAY_DISABLE_REMOTE_CODE=true RAY_SECURITY_CONFIG_PATH=config.yml RAY_USE_TLS=1 RAY_TLS_SERVER_CERT=servercert.pem RAY_TLS_SERVER_KEY=serverkey.pem RAY_TLS_CA_CERT=cacert.pem ray start --head --node-ip-address="192.168.137.4" --port="6379" --resources='{"alice": 8}' --include-dashboard=False --disable-usage-stats
Usage stats collection is disabled.

Local node IP: 192.168.137.4
E0714 07:48:09.783010834    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:09.783055834    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:09.783061834    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:09.783066534    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:10.785822614    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:10.785848214    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:10.785853214    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:10.785857714    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:11.787983491    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:11.788010492    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:11.788015492    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:11.788019492    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:12.790182069    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:12.790247570    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:12.790256170    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:12.790260470    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:13.792359247    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:13.792404647    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:13.792410247    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:13.792423847    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
E0714 07:48:14.794512125    8132 ssl_transport_security.cc:845] Invalid cert chain file.
E0714 07:48:14.794539725    8132 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0714 07:48:14.794545325    8132 chttp2_connector.cc:317]    Failed to create secure subchannel for secure name '192.168.137.4:6379'
E0714 07:48:14.794549725    8132 chttp2_connector.cc:276]    Failed to create channel args during subchannel creation.
2022-07-14 07:48:14,794	WARNING utils.py:1282 -- Unable to connect to GCS at 192.168.137.4:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
```

**Comment by longshan-ant** [comment] 2022-07-15 08:52
我看问题是和[41](https://github.com/secretflow/secretflow/issues/41)一样的，这里是不是可以先关掉？

**Comment by wuxibin89** [comment] 2022-07-19 07:32
见https://github.com/secretflow/secretflow/issues/40 讨论，你可以
-

**Comment by 6fj** [comment] 2022-07-28 02:27
Duplicate of #40

**Closed by 6fj** 2022-07-28 02:27 UTC
Labels: cluster
